---
title: "assign4"
output: html_notebook
---


For the regular expression exercises, try writing first using regular expressions directly, then try using rverbalexpressions. Provide the code for both. 

# Part 1

## R4DS 16.4.5

Create a vector of dates giving the first day of every month in the current year. 

Write a function that given your birthday (as a date), returns how old you are in years.

Write a function that given your birthday, returns the day of the week you were born on. 

## R4DS 14.3.2.1

Given the corpus of common words in stringr::words, create regular expressions that find all words that:

Start with “y”.

End with “x”

Have seven letters or more. (Since this list is long, you might want to use the match argument to str_view() to show only the matching or non-matching words.)

## R4DS 14.3.3.1

Use str_detect to find all words that:

That only contain consonants. (Hint: thinking about matching “not”-vowels.)

End with ed, but not with eed.

Empirically verify the rule “i before e except after c”.

Create a regular expression that will match telephone numbers as commonly written in the US. Split this up into multiple expressions as needed.

# Part 2


Choose a dataset (this can be the same dataset as the last assignment, or a new one). Define a predictive modeling problem. Create the appropriate files and notebooks to do the following:

1. Describe the data and the problem

2. Read in and check data

2. Clean up the data. 

*Note: You may request that score for these sections replace your score for the coding portion of Assignment 3.*

4. Using best practices, write four functions which add engineered features to the dataset, including a description and rationale. Include a test to determine whether the features are working as intended. 

5. Prepare the data for modeling

Note: this will form the basis for your midterm project. Take advantage of TA's and my office hours. We can provide feedback and guidance. 

